import { describe, expect, it } from 'vitest';
import { estimateWidth, recordBandStylesheet, spansAt, type CellRuns } from './record-band-43';
import { fillRows, packRecordBand } from './record-band-41';

/**
 * §43 (step 51): "The server renders the record band already packed, from
 * each cell's content, so first paint is the packed layout and nothing below
 * the band moves... The prose estimate uses the server's font metrics, not a
 * single average coefficient." The metrics are the page's own, measured with
 * its fonts loaded (`font-metrics.json`, generated by the capture tool).
 */
describe('§43: the server estimates each cell’s width from the font’s own metrics', () => {
  it('reproduces widths the page measured: the label register with its tracking, mono values, the year figure', () => {
    /* Measured on the page: "Provenance" 76, the matrix runout 274, "1970" 164 at 72px, "Paid $12.99" in prose. */
    /* Within 1.5%: the estimate sums advances and ignores kerning pairs, which the quarter rounding absorbs; "1970" at 72px kerns 2px tighter. */
    const within = (got: number, measured: number) => expect(Math.abs(got - measured) / measured, `${got.toFixed(1)} against measured ${measured}`).toBeLessThan(0.015);
    within(estimateWidth('Provenance', 'label'), 76);
    within(estimateWidth('269346E1 1701690 MP731-A JN-H STERLING', 'mono12'), 274);
    within(estimateWidth('1970', 'figure72'), 164);
    expect(estimateWidth('', 'prose')).toBe(0);
  });

  it('packs a cell by the widest of its runs, a wrapping run at most the cell’s measure, and states the quarters at a width', () => {
    const cells: CellRuns[] = [
      { name: 'provenance', runs: [{ text: 'Provenance', register: 'label' }, { text: 'Paid $12.99', register: 'prose' }] },
      { name: 'matrix', runs: [{ text: 'Matrix / runout', register: 'label' }, { text: '269346E1 1701690 MP731-A JN-H STERLING', register: 'mono12', wraps: true }] },
      { name: 'year', runs: [{ text: 'Released · same year', register: 'label' }, { text: '2024', register: 'figure72' }] },
      { name: 'market', runs: [{ text: 'Market median', register: 'label' }, { text: '$3.95', register: 'figure40' }] },
      { name: 'note', runs: [{ text: 'About', register: 'label' }, { text: 'A sentence about the record that goes on. '.repeat(20), register: 'prose', wraps: true }] },
    ];
    /* At 1000 a quarter is 250: the runout (274 + 36) needs two, so the first row is 1 + 2 + 1; the market starts a row alone and takes it (§42); the About wraps to the row. */
    expect(spansAt(cells, 1000)).toEqual([1, 2, 1, 4, 4]);
    /* At 1439 a quarter is 359.75: the runout fits one, so the four fit one row and the market ends it. */
    expect(spansAt(cells, 1439)).toEqual([1, 1, 1, 1, 4]);
    /* The same numbers the page's model gives for those estimates, rows filled. */
    const ink = (c: CellRuns, w: number) => Math.max(0, ...c.runs.map((r) => (r.wraps ? Math.min(estimateWidth(r.text, r.register), w - 36) : estimateWidth(r.text, r.register))));
    expect(spansAt(cells, 1000)).toEqual(fillRows(packRecordBand({ quarter: 250, padding: 18, cells: cells.map((c) => ({ ink: ink(c, 1000), label: 0 })) })));
  });

  it('emits one stylesheet covering 960 to 1439 without a gap, changing only where a cell crosses a quarter', () => {
    const cells: CellRuns[] = [
      { name: 'provenance', runs: [{ text: 'Provenance', register: 'label' }] },
      { name: 'matrix', runs: [{ text: '269346E1 1701690 MP731-A JN-H STERLING', register: 'mono12', wraps: true }] },
      { name: 'note', runs: [{ text: 'About', register: 'label' }] },
    ];
    const css = recordBandStylesheet(cells);
    const ranges = [...css.matchAll(/@media \(min-width: (\d+)px\) and \(max-width: (\d+)px\)/g)].map((m) => [Number(m[1]), Number(m[2])]);
    expect(ranges.length, 'at least one range').toBeGreaterThan(0);
    expect(ranges[0][0], 'starts at 960').toBe(960);
    expect(ranges[ranges.length - 1][1], 'ends at 1439').toBe(1439);
    for (let k = 1; k < ranges.length; k += 1) expect(ranges[k][0], 'contiguous').toBe(ranges[k - 1][1] + 1);
    /* The runout crosses from two quarters to one where 4 × (its width + 36) is the band's width: a range boundary sits there. */
    const cross = Math.ceil(4 * (estimateWidth('269346E1 1701690 MP731-A JN-H STERLING', 'mono12') + 36));
    expect(ranges.some(([a]) => a === cross), `a range starts at ${cross} (${ranges.map((r) => r.join('-')).join(', ')})`).toBe(true);
    expect(css, 'states the matrix at two quarters below it').toMatch(/\(min-width: 960px\)[^}]*\{[\s\S]*?\[data-cell="matrix"\] \{ --packed: 2;/);
    expect(css, 'and one from it').toMatch(new RegExp(`\\(min-width: ${cross}px\\)[\\s\\S]*?\\[data-cell="matrix"\\] \\{ --packed: 1;`));
    /* The last cell in a row fills it, and rules stand between rendered cells (§42): stated in the same sheet. */
    expect(css).toMatch(/--rule-right: 1px/);
    expect(css).toMatch(/--rule-top: (0|1)px/);
  });
});
