import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // CLAUDE.md §6 bans console.* in committed code in favour of a logger module.
  // Enforced rather than trusted: the rule is why src/lib/logger.ts exists.
  {
    files: ["src/**/*.ts", "src/**/*.tsx"],
    ignores: ["src/lib/logger.ts", "src/**/*.test.ts", "src/**/*.test.tsx"],
    rules: { "no-console": "error" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    // The E2E dev server's build directory (next.config.ts sets `distDir` under
    // NODE_ENV=test so it can run alongside the developer's dev server).
    // eslint-config-next ignores `.next` by name and knows nothing about this
    // one, so without the entry lint walks 765MB of generated output and
    // reports ~1,550 errors in code nobody wrote. Same reasoning as
    // playwright-report below.
    ".next-test/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Playwright, git-ignored, and not ours to lint. Without this
    // the bundled trace viewer contributes ~250 errors and lint output stops
    // being readable. Reachable since the `html` reporter began writing on
    // green runs too.
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
