-- SPEC.md §4.2 as amended by A21a, and §10b: `image_type`'s `gatefold` value
-- becomes `gatefold_left` and `gatefold_right`.
--
-- WHY: §10b specifies the gatefold inner as TWO square photographs rather than
-- one wide spread. A real inner is continuous and a single spread would be more
-- faithful, but it asks for a shot most phones take badly and makes the inner
-- the only non-square image in the collection. Two straight-on photographs are
-- what someone can actually take. The accepted cost is a seam down the middle
-- where the two differ in lighting or crop.
--
-- The affordance now requires BOTH leaves (§10b): a hinge opening onto artwork
-- on one side and a blank on the other invents exactly the thing the reader
-- came to see.
--
-- DESTRUCTIVE TYPE CHANGE, flagged per CLAUDE.md §7 and confirmed before
-- writing. Postgres cannot remove a value from an enum in place, so the type is
-- replaced. Forward-only: 0011 added `gatefold` and is never edited.
--
-- IT CARRIES NO DATA, AND THAT WAS MEASURED RATHER THAN ASSUMED. Production
-- Neon held 2 rows in `images` at the time of writing, both `cover`: zero
-- `gatefold`, zero `back`. So no row needs remapping and the hard case — a
-- `gatefold` row that could be either leaf, with nothing in the data to say
-- which — does not arise. The local test database is truncated between runs and
-- its count would have proved nothing (NOTES).
--
-- Generated by `drizzle-kit generate`, then renamed with its journal tag fixed.
-- Hand-writing the SQL and appending the journal entry leaves the snapshot
-- missing, and `drizzle-kit migrate` then prints "migrations applied
-- successfully" and applies nothing (NOTES).
--
-- The two leaves sit together after `back` and before the close-ups, so the
-- enum reads in the order a sleeve is examined: front, back, inside, then the
-- detail shots. `schema.test.ts` asserts that ORDER, not only membership.

ALTER TABLE "images" ALTER COLUMN "image_type" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "public"."image_type";--> statement-breakpoint
CREATE TYPE "public"."image_type" AS ENUM('cover', 'back', 'gatefold_left', 'gatefold_right', 'label', 'matrix', 'other');--> statement-breakpoint
ALTER TABLE "images" ALTER COLUMN "image_type" SET DATA TYPE "public"."image_type" USING "image_type"::"public"."image_type";