/**
 * Generates NOTES.md's apparatus index from the entries themselves.
 *
 * **The problem this solves, measured.** NOTES is 29,000 lines and 401 entries.
 * Its apparatus rules — the part that has paid for itself repeatedly — are each
 * titled as their own CONCLUSION: "A test that measures a set constrains no
 * member of it", "A timeout standing in for a state is latent until someone
 * changes a constant". Those are findable if you already know them, which is
 * backwards for a document whose value is recognising a shape BEFORE paying for
 * it again. A classifier written against the titles could not find them, and
 * that is the test of findability failing.
 *
 * So the index is keyed by the CIRCUMSTANCE a reader is in, not by the rule's
 * name: "I have a test that passes and I am not sure it is testing anything"
 * rather than "a test that measures a set constrains no member of it".
 *
 * **Generated, never hand-maintained.** A hand-written index of a 29,000-line
 * file is stale within a week and then actively misleading — worse than none,
 * because a reader trusts it. `test/repo/notes-index.test.ts` fails when the
 * committed index does not match what this produces.
 *
 * Entries opt in by declaring two lines directly under their heading:
 *
 *     **Shape:** check-cannot-fail
 *     **You are here if:** a test passes and you cannot say what would break it
 *
 * Nothing else in an entry changes, and **no rule is compressed** — the index
 * points at the entry, which keeps its evidence. A rule without the instance
 * that produced it is a rule the next reader argues with.
 *
 * **Two rules sharing a circumstance is anticipated and unhandled.** It has not
 * occurred across 61 entries, so a guard for it would be speculative. If it
 * arises the index renders two rows with identical left cells, which reads
 * correctly — a situation that forks, with both rules reachable from it. That is
 * the intended behaviour rather than a duplication to resolve, and it is left
 * alone deliberately.
 */

import { readFileSync, writeFileSync } from 'node:fs';

/** The kinds of thing going wrong, in the order a reader meets them. */
export const SHAPES = [
  'measurement-not-governing',
  'check-cannot-fail',
  'wrong-axis-variation',
  'observer-without-subject',
  'sample-as-population',
  'instrument-reports-nothing',
] as const;

export type Shape = (typeof SHAPES)[number];

export const SHAPE_TITLES: Record<Shape, string> = {
  'measurement-not-governing': 'Measurements that do not govern',
  'check-cannot-fail': 'Checks that cannot fail',
  'wrong-axis-variation': 'Variation applied to the wrong axis',
  'observer-without-subject': 'Observers satisfied without a subject',
  'sample-as-population': 'Samples read as populations',
  'instrument-reports-nothing': 'Instruments that report nothing',
};

export type IndexedRule = {
  shape: Shape;
  circumstance: string;
  title: string;
  /** Where the rule lives, so the evidence travels with it. */
  anchor: string;
  lines: number;
};

/** A GitHub-style anchor for a markdown heading. */
export function anchorFor(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

export function readRules(markdown: string): IndexedRule[] {
  const lines = markdown.split('\n');
  const heads: Array<{ line: number; title: string }> = [];
  for (const [index, line] of lines.entries()) {
    if (line.startsWith('## ')) heads.push({ line: index, title: line.slice(3).trim() });
  }

  const rules: IndexedRule[] = [];
  for (const [n, head] of heads.entries()) {
    const end = n + 1 < heads.length ? heads[n + 1].line : lines.length;
    const body = lines.slice(head.line, end);

    const shapeLine = body.find((l) => l.startsWith('**Shape:**'));
    const whereLine = body.find((l) => l.startsWith('**You are here if:**'));
    if (shapeLine === undefined || whereLine === undefined) continue;

    const shape = shapeLine.replace('**Shape:**', '').trim() as Shape;
    if (!SHAPES.includes(shape)) {
      throw new Error(
        `"${head.title}" declares an unknown shape "${shape}". Known: ${SHAPES.join(', ')}.`,
      );
    }

    rules.push({
      shape,
      circumstance: whereLine.replace('**You are here if:**', '').trim(),
      title: head.title,
      anchor: anchorFor(head.title),
      lines: end - head.line,
    });
  }

  return rules;
}

/** The index, as the markdown block that lives at the top of NOTES.md. */
const START = '<!-- APPARATUS-INDEX:START';
const END = '<!-- APPARATUS-INDEX:END -->';

export function renderIndex(rules: IndexedRule[]): string {
  const out: string[] = [
    '<!-- APPARATUS-INDEX:START — generated by scripts/notes-index.ts, do not edit -->',
    '',
    '## The apparatus index',
    '',
    '**Find a rule by the situation you are in, not by its name.** Every rule below',
    'is titled as its own conclusion, which makes it findable only if you already',
    'know it — so this table is keyed by the circumstance instead. Each entry keeps',
    'its evidence: follow the link rather than trusting the line.',
    '',
    '**Checks that cannot fail is the largest shape by a distance**, and with',
    '*instruments that report nothing* it is close to half of everything recorded',
    'here. They are one defect seen from two sides: an assertion with no failing',
    'input, and an observation with no subject. Both produce green. If you are',
    'looking at something that passes and you are not sure why, start in those two.',
    '',
    `Generated from ${rules.length} declared rules. Regenerate with`,
    '`npx tsx scripts/notes-index.ts --write`.',
    '',
  ];

  for (const shape of SHAPES) {
    const group = rules.filter((r) => r.shape === shape);
    if (group.length === 0) continue;

    out.push(`### ${SHAPE_TITLES[shape]}`, '');
    out.push('| You are here if | The rule |', '| --- | --- |');
    for (const rule of group.sort((a, b) => a.title.localeCompare(b.title))) {
      out.push(`| ${rule.circumstance} | [${rule.title}](#${rule.anchor}) |`);
    }
    out.push('');
  }

  out.push('<!-- APPARATUS-INDEX:END -->');
  return out.join('\n');
}

/* A CLI, because a library invoked as a command is a concealment this repo has
   already paid for once (scripts/run-tests.ts). */
/**
 * The generated block spliced between the markers, the rest of the file
 * untouched. Exported so the write path is the same text the check compares.
 */
export function spliceIndex(markdown: string): string {
  const start = markdown.indexOf(START);
  const end = markdown.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`no index block: expected ${START} ... ${END}`);
  }
  return markdown.slice(0, start) + renderIndex(readRules(markdown)) + markdown.slice(end + END.length);
}

if (process.argv[1]?.endsWith('notes-index.ts')) {
  /*
    `--write [path]` splices in place; without it the index is printed. For as
    long as the footer said "Regenerate with --write" the flag did nothing
    (29 Sep) — a documented flag no code implements is a check that cannot
    fail, and the block was being spliced by hand.
  */
  const args = process.argv.slice(2);
  const write = args.includes('--write');
  const path = args.find((a) => a !== '--write') ?? 'NOTES.md';
  const markdown = readFileSync(path, 'utf8');
  const rules = readRules(markdown);
  if (write) {
    writeFileSync(path, spliceIndex(markdown));
    process.stdout.write(`${path}: index written.\n`);
  } else {
    process.stdout.write(renderIndex(rules));
    process.stdout.write('\n');
  }
  process.stdout.write(`\n${rules.length} rules indexed.\n`);
}
