#!/usr/bin/env node
/**
 * What changed between two readings of the screens' survey sheet
 * (`e2e/sheet/screens-survey.sheet.ts`), per screen, state and window.
 *
 *     node scripts/survey-diff.mjs <before>/survey.json <after>/survey.json > diff.md
 *
 * For each: the page's length, and, for text sizes, text colours, fills,
 * borders and corner radii, every value whose count of elements changed,
 * with what carried it before and after. A screen where nothing changed
 * says so in one line, so "unchanged" is a reading and not an omission.
 */
import { readFileSync } from 'node:fs';

const [before, after] = process.argv.slice(2).map((p) => JSON.parse(readFileSync(p, 'utf8')));
const NAMES = {
  'lab(24.7078 31.5572 12.9848)': 'oxblood',
  'lab(39.6559 2.06429 4.02272)': 'the survey’s grey',
  'lab(6.18075 1.20374 2.12039)': 'ink',
  'oklch(0.19 0.008 60)': 'ink',
  'lab(35.0433 0.937879 2.8959)': 'the label colour',
  'oklch(0.44 0.008 70)': 'the label colour',
  'lab(97.7005 0.135839 1.90169)': 'the near-white set on oxblood',
  'lab(67.5318 0.226438 1.50546)': 'the hairline',
  'oklch(0.72 0.004 80)': 'the hairline',
  'lab(91.3119 0.225008 1.50455)': 'paper',
  'oklch(0.925 0.004 80)': 'paper',
  'rgba(0, 0, 0, 0)': 'transparent',
};
const name = (key) => Object.entries(NAMES).reduce((k, [raw, n]) => k.replace(raw, `${n} [${raw}]`), key);
const total = (on) => (on === undefined ? 0 : typeof on.count === 'number' ? on.count : Object.values(on).reduce((a, b) => a + b, 0));
const carried = (on) => (on === undefined ? 'nothing' : Object.entries(on.carries ?? on).map(([w, n]) => `${w} ${n}`).join(', '));
const id = (r) => `${r.screen} | ${r.state} | ${r.width}`;
const afterBy = new Map(after.map((r) => [id(r), r]));

const out = ['# What changed between the two readings', '', 'Generated by `scripts/survey-diff.mjs`. Counts are elements; a value is listed where its count changed.', ''];
const unchanged = [];
for (const b of before) {
  const a = afterBy.get(id(b));
  if (a === undefined) { out.push(`## ${b.screen}, ${b.state}, at ${b.width}`, '', 'Not in the second reading.', ''); continue; }
  const lines = [];
  if (b.pageHeight !== a.pageHeight) lines.push(`- page length ${b.pageHeight} → ${a.pageHeight}`);
  if (b.pageWidth !== a.pageWidth) lines.push(`- page width ${b.pageWidth} → ${a.pageWidth}`);
  for (const [label, key] of [['text size', 'type'], ['text colour', 'textColours'], ['fill', 'fills'], ['border', 'borders'], ['corner radius', 'radii']]) {
    for (const value of [...new Set([...Object.keys(b[key]), ...Object.keys(a[key])])].sort()) {
      const [n0, n1] = [total(b[key][value]), total(a[key][value])];
      if (n0 === n1) continue;
      lines.push(`- ${label} ${name(value)}: ${n0} → ${n1} (was on ${carried(b[key][value])}; now on ${carried(a[key][value])})`);
    }
  }
  if (lines.length === 0) unchanged.push(`${b.screen}, ${b.state}, at ${b.width}`);
  else out.push(`## ${b.screen}, ${b.state}, at ${b.width}`, '', ...lines, '');
}
out.splice(4, 0, '## Unchanged in every measure read', '', ...(unchanged.length === 0 ? ['None.'] : unchanged.map((u) => `- ${u}`)), '');
process.stdout.write(`${out.join('\n')}\n`);
